name: Iman
version: '${project.version}'
description: '${project.description}'
author: maksim2498
main: space.moontalk.mc.iman.Iman
database: true
api-version: 1.13
commands:
  inventory:
    aliases: [inv]
    description: Manages inventories
    permission-message: "§cYou don't have permission to run this command."
    usage: |
      /<command> list [player name]
      /<command> set <inventory name> [player name]
      /<command> save <inventory name> [player name]
permissions:
  iman.inv.list.self:
    description: Allowes you to list your own invenotries.
    default: true
  iman.inv.list.other:
    description: Allowes you to list other players' invenotries.
    default: op 
  iman.inv.save.self:
    description: Allowes you to save your own inventory.
    default: op
  iman.inv.save.other:
    description: Allowes you to save other players' inventory.
    default: op
  iman.inv.set.self:
    description: Allowes you to set your own inventory.
    default: op
  iman.inv.set.other:
    description: Allowes you to set other players' inventory.
    default: op
