name: Iman
main: space.moontalk.mc.iman.Iman
version: '${project.version}'
api-version: 1.13
description: '${project.description}'
author: maksim2498
commands:
  inventory:
    aliases: [inv]
    description: Manages inventories
    permission-message: "§cYou don't have permission to run this command."
    usage: |
      /<command> list [player name]
      /<command> set <inventory name> [player name]
      /<command> save <inventory name> [player name]
